apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scalingmonitor
  labels: {app: scalingmonitor}
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata: {labels: {app: scalingmonitor}}
    spec:
      containers:
      - name: scalingmonitor
        image: docker.io/cptplaneta/scalingmonitor:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: scalingmonitor
  namespace: kube-system
spec:
  type: NodePort
  selector: 
    app: scalingmonitor
  ports:
  - port: 8000
    targetPort: 8000
